// Generated by scripts/routers.mjs from Zerion swap quotes. Do not edit by hand: rerun `npm run routers`.
// This is the allowlist validateQuoteCalls trusts. Review every added address (git diff) before committing.
// Wallet sampled: 0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045
import type { Address } from 'viem'
import type { ChainId } from '@/lib/chains'

export type Router = { address: Address; sources: readonly string[] }

export const ROUTERS: Record<ChainId, readonly Router[]> = {
  'base': [
    { address: '0x0000000000001ff3684f28c67538d4d072c22734', sources: ['0x'] },
    { address: '0x111111125421ca6dc452d289314280a0f8842a65', sources: ['1inch'] },
    { address: '0x6131b5fae19ea4f9d964eac0408e4408b66337b5', sources: ['kyber'] },
  ],
  'arbitrum': [
    { address: '0x0000000000001ff3684f28c67538d4d072c22734', sources: ['0x'] },
    { address: '0x111111125421ca6dc452d289314280a0f8842a65', sources: ['1inch'] },
    { address: '0x6131b5fae19ea4f9d964eac0408e4408b66337b5', sources: ['kyber'] },
  ],
  'optimism': [
    { address: '0x0000000000001ff3684f28c67538d4d072c22734', sources: ['0x'] },
    { address: '0x111111125421ca6dc452d289314280a0f8842a65', sources: ['1inch'] },
    { address: '0x6131b5fae19ea4f9d964eac0408e4408b66337b5', sources: ['kyber'] },
  ],
  'polygon': [
    { address: '0x0000000000001ff3684f28c67538d4d072c22734', sources: ['0x'] },
    { address: '0x111111125421ca6dc452d289314280a0f8842a65', sources: ['1inch'] },
    { address: '0x6131b5fae19ea4f9d964eac0408e4408b66337b5', sources: ['kyber'] },
  ],
  'binance-smart-chain': [
    { address: '0x0000000000001ff3684f28c67538d4d072c22734', sources: ['0x'] },
    { address: '0x6131b5fae19ea4f9d964eac0408e4408b66337b5', sources: ['kyber'] },
  ],
}
